### ISSUE TITLE
Suggestion: make print-instance-readably a generic function

### ISSUE THREAD

**Issue by rpgoldman** [phoe/phoe-toolbox#5]
If this is replaced by a generic function, the programmer can extend it to make `define-readable-print` work for classes that can't be serialized by the built-in method. This could be simply done by making the function generic and taking the existing function body and using it as the default method (on `standard-object`).  Then the programmer could, for example, take a class that has super classes, and extend the default method to save not just the direct slots, but indirect slots, as well.  To make this work better, you might try splitting out the guts of this method into a function something like "serialize direct slots." Then the programmer could write methods that would use that function to serialize direct slots, and `call-next-method` to get superclass slots.
Just a suggestion.

**Comment by phoe** [comment]
I have never thought that anyone beside me might be using this function, let alone think of extending it.

Your suggestion is very valid though and it should be possible to define methods on it, and `PRINT-HASH-TABLE-READABLY` should simply be a method on that function instead.

Will do when I have a spare while, thanks for the report!

**Comment by phoe** [comment]
Once again, thank you for the suggestion!
